"""Python port of the flat Julia :mod:`SLMTools` module.

The public wildcard surface intentionally contains the same 100 names as
SLMTools.jl 0.3.0.  Useful Julia-qualified helpers such as ``gsError`` and the
basis functions remain available as package or submodule attributes without
changing that compatibility list.
"""

from __future__ import annotations

from .lattice_field import (
    Amplitude,
    ComplexAmp,
    ComplexAmplitude,
    ComplexPhase,
    DimensionMismatch,
    DomainError,
    FieldVal,
    Generic,
    Intensity,
    LF,
    Lattice,
    LatticeAxis,
    LatticeField,
    Modulus,
    Phase,
    RealAmp,
    RealAmplitude,
    RealPhase,
    S1Phase,
    UPhase,
    UnwrappedPhase,
    elq,
    normalizeLF,
    phasor,
    square,
    subfield,
    sublattice,
    wrap,
)
from .lattice_utils import (
    FrFTBasis,
    Nyquist,
    hermiteBasis,
    latticeDisplacement,
    ldot,
    natlat,
    naturalize,
    natrange,
    padout,
    r2,
    shiftedDFTBasis,
    toDim,
    wigner_fft,
)
from .resampling import (
    CubicSplineInterpolation,
    Flat,
    Linear,
    LinearInterpolation,
    Periodic,
    coarsen,
    cubic_spline_interpolation,
    downsample,
    upsample,
)
from .dual_lattices import dualLattice, dualPhase, dualShiftLattice, isft, ldq, sft
from .misc import SchroffError, centroid, clip, collapse, nabs, ramp, safeInverse, window
from .image_processing import (
    castImage,
    dualate,
    getImagesAndFilenames,
    getOrientation,
    imageToFloatArray,
    itfa,
    linearFit,
    loadDir,
    parseFileName,
    parseStringToNum,
    saveBeam,
    savePhase,
    savePhase8BMP,
)
from .templates import (
    ftaText,
    heartQ,
    lfBlur,
    lfCap,
    lfGaussian,
    lfHeart,
    lfParabola,
    lfPointer,
    lfRand,
    lfRect,
    lfRing,
    lfSmile,
    lfText,
    pointerFillQ,
    pointerOutlineQ,
    smileQ,
)
from .ift import gs, gsError, gsIter, gsLog, mraf, oneShot, pdgs, pdgsError, pdgsIter, pdgsLog
from .ot import (
    SinkhornConvN,
    SinkhornIterBase as _SinkhornIterBase,
    dualToGradients,
    getCostMatrix,
    hyperSum,
    hyperSum2,
    mapify,
    normalizeDistribution,
    otPhase,
    otPhase2,
    otQuickPhase,
    pdCostMatrix,
    pdotBeamEstimate,
    pdotPhase,
    scalarPotentialN,
)
from .visualization import _cycle1 as cycle1, look
from .bmp8 import save_gray8bmp

__version__ = "0.3.0"
JULIA_SOURCE_COMMIT = "ea1c1c9c06b4b2dc46372ac7ee031301b604a007"

# Julia-qualified helpers that are intentionally absent from its ``export``
# declarations remain package attributes without entering ``__all__``.
rampPrivate = ramp
from .templates import _l2form as l2form, _standard_output as lfStandardOutputFormat
globals()["SinkhornIterBase!"] = _SinkhornIterBase

# This order follows the Julia module's include order and per-file exports.
JULIA_EXPORTS = (
    "Lattice",
    "elq",
    "RealPhase",
    "Generic",
    "Phase",
    "FieldVal",
    "ComplexPhase",
    "UPhase",
    "UnwrappedPhase",
    "S1Phase",
    "Intensity",
    "Amplitude",
    "Modulus",
    "RealAmplitude",
    "RealAmp",
    "ComplexAmplitude",
    "ComplexAmp",
    "LatticeField",
    "LF",
    "normalizeLF",
    "phasor",
    "subfield",
    "wrap",
    "square",
    "sublattice",
    "natrange",
    "natlat",
    "padout",
    "latticeDisplacement",
    "toDim",
    "naturalize",
    "r2",
    "ldot",
    "Nyquist",
    "downsample",
    "coarsen",
    "upsample",
    "dualLattice",
    "dualShiftLattice",
    "dualPhase",
    "ldq",
    "sft",
    "isft",
    "ramp",
    "nabs",
    "window",
    "safeInverse",
    "centroid",
    "collapse",
    "clip",
    "SchroffError",
    "getImagesAndFilenames",
    "imageToFloatArray",
    "itfa",
    "castImage",
    "loadDir",
    "parseFileName",
    "parseStringToNum",
    "getOrientation",
    "dualate",
    "linearFit",
    "savePhase",
    "saveBeam",
    "savePhase8BMP",
    "lfParabola",
    "lfGaussian",
    "lfRing",
    "lfCap",
    "ftaText",
    "lfText",
    "lfRect",
    "lfRand",
    "lfHeart",
    "lfSmile",
    "lfPointer",
    "lfBlur",
    "gs",
    "gsIter",
    "gsLog",
    "pdgs",
    "pdgsIter",
    "pdgsLog",
    "oneShot",
    "pdgsError",
    "mraf",
    "getCostMatrix",
    "pdCostMatrix",
    "pdotPhase",
    "pdotBeamEstimate",
    "mapify",
    "scalarPotentialN",
    "otPhase",
    "hyperSum2",
    "otQuickPhase",
    "SinkhornConvN",
    "dualToGradients",
    "normalizeDistribution",
    "otPhase2",
    "look",
    "save_gray8bmp",
)

assert len(JULIA_EXPORTS) == 100 and len(set(JULIA_EXPORTS)) == 100
__all__ = list(JULIA_EXPORTS)
